### ISSUE TITLE
initial button state broken

### ISSUE THREAD

**Issue by nomisum** [Fusselwurm/nodebb-plugin-attendance#9]
http://i.imgur.com/iG4sNVE.png (Synch @Chrome)

**Comment by nomisum** [comment]
Seems to be the case in M$ Edge too.

I was able to solve this by clicking "yes" in both browsers, but Synch said it didnt work for him.

Maybe begin debugging at initial state (unknown state)

**Comment by Fusselwurm** [comment]
![_20170107_084638](https://cloud.githubusercontent.com/assets/52833/21740299/4a1f588e-d4b6-11e6-80f4-68d7b010b43f.JPG)

Android 5.1, Chrome 55

**Comment by nomisum** [comment]
can reproduce on FF too, so probably a logic problem slipping through

**Comment by nomisum** [comment]
fixed in dev
